[fcitx5-anthy]
source="github"
github="fcitx/fcitx5-anthy"
use_latest_tag=true

[fcitx5-bamboo]
source="github"
github="fcitx/fcitx5-bamboo"
use_latest_tag=true

[fcitx5-chewing]
source="github"
github="fcitx/fcitx5-chewing"
use_latest_tag=true

[fcitx5-chinese-addons]
source="github"
github="fcitx/fcitx5-chinese-addons"
use_latest_tag=true

[fcitx5-configtool]
source="github"
github="fcitx/fcitx5-configtool"
use_latest_tag=true

[fcitx5-gtk]
source="github"
github="fcitx/fcitx5-gtk"
use_latest_tag=true

[fcitx5-hangul]
source="github"
github="fcitx/fcitx5-hangul"
use_latest_tag=true

[fcitx5-kkc]
source="github"
github="fcitx/fcitx5-kkc"
use_latest_tag=true

[fcitx5-lua]
source="github"
github="fcitx/fcitx5-lua"
use_latest_tag=true

[fcitx5-m17n]
source="github"
github="fcitx/fcitx5-m17n"
use_latest_tag=true

[fcitx5-qt]
source="github"
github="fcitx/fcitx5-qt"
use_latest_tag=true

[fcitx5-rime]
source="github"
github="fcitx/fcitx5-rime"
use_latest_tag=true

[fcitx5-table-extra]
source="github"
github="fcitx/fcitx5-table-extra"
use_latest_tag=true

[fcitx5-table-other]
source="github"
github="fcitx/fcitx5-table-other"
use_latest_tag=true

[fcitx5-unikey]
source="github"
github="fcitx/fcitx5-unikey"
use_latest_tag=true

[ibus-libpinyin]
source="github"
github="libpinyin/ibus-libpinyin"
use_latest_release=true
exclude_regex = ".*(dev|rc|RC|alpha|beta).*"
