on:
  schedule:
     - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  update_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: codeberg.org/lindsay/act:alpine-3.22
    steps:
      - name: install tools
        run: |
          apk add --no-cache nvchecker

      - uses: actions/checkout@v5
        
      - name: write keyfile
        run: |
          cat > keyfile.toml << EOF
          [keys]
          github="${{secrets.GITHUB_TOKEN}}"
          EOF

      - name: generate configure
        run: |
          cat ./nvcheck/*.toml > ./nvchecker.toml

      - name: check update & notify
        env:
          NTFY_ENDPOINT: "${{secrets.NTFY_ENDPOINT}}"
          NTFY_TOKEN: "${{secrets.NTFY_TOKEN}}"
        run: ./check.py ./nvchecker.toml

      - name: save updates
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if [[ `git status --porcelain` ]]; then
            git add old_ver.json new_ver.json
            git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
            git commit -m "Update package list"
            git push github HEAD:master -f
          fi
